import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useParams } from 'react-router-dom';
import { Battery, Waves, Radio, Activity, } from 'lucide-react';
import WaterLevelChart from '@/components/dashboard/WaterLevelChart';
import { useDepositHistory, } from '@/hooks/useDepositHistory';
import { useDeposit, } from '@/hooks/useDeposit';
const DepositDetailPage = () => {
    const { id } = useParams();
    const { deposit, loading: depositLoading, } = useDeposit(id ?? '');
    const { history, loading: historyLoading, } = useDepositHistory(id ?? '');
    if (depositLoading) {
        return (_jsx("div", { className: "text-white", children: "Cargando dep\u00F3sito..." }));
    }
    if (!deposit) {
        return (_jsx("div", { className: "text-white", children: "Dep\u00F3sito no encontrado" }));
    }
    return (_jsxs("div", { className: "\r\n      flex\r\n      flex-col\r\n      gap-8\r\n      w-full\r\n    ", children: [_jsxs("div", { className: "\r\n        flex\r\n        flex-col\r\n        gap-2\r\n      ", children: [_jsx("h2", { className: "\r\n          text-4xl\r\n          font-black\r\n          tracking-tight\r\n        ", children: deposit.name }), _jsx("p", { className: "\r\n          text-gray-400\r\n          text-lg\r\n        ", children: "Monitorizaci\u00F3n industrial en tiempo real" })] }), _jsxs("div", { className: "\r\n        grid\r\n        grid-cols-1\r\n        xl:grid-cols-[380px_1fr]\r\n        gap-6\r\n      ", children: [_jsxs("div", { className: "\r\n          relative\r\n\r\n          overflow-hidden\r\n\r\n          bg-gradient-to-br\r\n          from-slate-800\r\n          to-slate-900\r\n\r\n          border\r\n          border-blue-900/30\r\n\r\n          rounded-3xl\r\n\r\n          p-8\r\n\r\n          shadow-2xl\r\n          shadow-black/30\r\n        ", children: [_jsx("div", { className: "\r\n            absolute\r\n            top-0\r\n            left-0\r\n\r\n            w-full\r\n            h-[2px]\r\n\r\n            bg-gradient-to-r\r\n            from-cyan-400\r\n            via-blue-500\r\n            to-cyan-400\r\n          " }), _jsxs("div", { className: "\r\n            flex\r\n            flex-col\r\n            items-center\r\n            gap-8\r\n          ", children: [_jsx("div", { className: "\r\n              relative\r\n\r\n              w-[160px]\r\n              h-[320px]\r\n\r\n              rounded-[36px]\r\n\r\n              border-[6px]\r\n              border-white/40\r\n\r\n              overflow-hidden\r\n\r\n              bg-slate-950\r\n            ", children: _jsx("div", { className: "\r\n                  absolute\r\n                  bottom-0\r\n                  left-0\r\n\r\n                  w-full\r\n\r\n                  bg-gradient-to-t\r\n                  from-blue-700\r\n                  via-blue-500\r\n                  to-cyan-400\r\n\r\n                  transition-all\r\n                  duration-700\r\n\r\n                  overflow-hidden\r\n\r\n                  shadow-inner\r\n                  shadow-cyan-300/20\r\n                ", style: {
                                                height: `${deposit.percentage}%`,
                                            }, children: _jsx("div", { className: "\r\n                  absolute\r\n                  top-[-12px]\r\n                  left-[-20%]\r\n\r\n                  w-[140%]\r\n                  h-[24px]\r\n\r\n                  rounded-full\r\n\r\n                  bg-white/20\r\n\r\n                  animate-pulse\r\n                " }) }) }), _jsxs("div", { className: "\r\n              text-center\r\n            ", children: [_jsxs("div", { className: "\r\n                text-6xl\r\n                font-black\r\n                text-white\r\n              ", children: [deposit.percentage
                                                        .toFixed(1), "%"] }), _jsx("div", { className: "\r\n                text-gray-400\r\n                mt-2\r\n              ", children: "Nivel actual" })] })] })] }), _jsxs("div", { className: "\r\n          flex\r\n          flex-col\r\n          gap-6\r\n        ", children: [_jsxs("div", { className: "\r\n            grid\r\n            grid-cols-1\r\n            md:grid-cols-2\r\n            gap-6\r\n          ", children: [_jsxs("div", { className: "\r\n            bg-gradient-to-br\r\n            from-slate-800\r\n            to-slate-900\r\n\r\n            border\r\n            border-blue-900/30\r\n\r\n            rounded-3xl\r\n\r\n            p-6\r\n\r\n            shadow-xl\r\n            shadow-black/20\r\n          ", children: [_jsxs("div", { className: "\r\n              flex\r\n              items-center\r\n              gap-3\r\n\r\n              mb-6\r\n            ", children: [_jsx(Radio, { size: 24, className: "\r\n                  text-cyan-400\r\n                " }), _jsx("h3", { className: "\r\n                text-2xl\r\n                font-bold\r\n                text-white\r\n              ", children: "Informaci\u00F3n LoRaWAN" })] }), _jsxs("div", { className: "\r\n              grid\r\n              grid-cols-1\r\n              md:grid-cols-2\r\n              gap-6\r\n            ", children: [_jsxs("div", { className: "\r\n                flex\r\n                flex-col\r\n                gap-2\r\n              ", children: [_jsx("span", { className: "\r\n                  text-gray-400\r\n                  text-sm\r\n                ", children: "Device EUI" }), _jsx("span", { className: "\r\n                  text-lg\r\n                  font-bold\r\n                  text-white\r\n                  break-all\r\n                ", children: deposit.deviceEui
                                                                    ?? 'Sin datos' })] }), _jsxs("div", { className: "\r\n                flex\r\n                flex-col\r\n                gap-2\r\n              ", children: [_jsx("span", { className: "\r\n                  text-gray-400\r\n                  text-sm\r\n                ", children: "Device Name" }), _jsx("span", { className: "\r\n                  text-lg\r\n                  font-bold\r\n                  text-white\r\n                ", children: deposit.deviceName
                                                                    ?? 'Sin datos' })] }), _jsxs("div", { className: "\r\n                flex\r\n                flex-col\r\n                gap-2\r\n              ", children: [_jsx("span", { className: "\r\n                  text-gray-400\r\n                  text-sm\r\n                ", children: "Gateway Time" }), _jsx("span", { className: "\r\n                  text-lg\r\n                  font-bold\r\n                  text-white\r\n                ", children: deposit.gatewayTime
                                                                    ?? 'Sin datos' })] }), _jsxs("div", { className: "\r\n                flex\r\n                flex-col\r\n                gap-2\r\n              ", children: [_jsx("span", { className: "\r\n                  text-gray-400\r\n                  text-sm\r\n                ", children: "Radar RSSI" }), _jsx("span", { className: "\r\n                  text-lg\r\n                  font-bold\r\n                  text-white\r\n                ", children: deposit.radarSignalRssi
                                                                    ?? 'Sin datos' })] }), _jsxs("div", { className: "\r\n                flex\r\n                flex-col\r\n                gap-2\r\n              ", children: [_jsx("span", { className: "\r\n                  text-gray-400\r\n                  text-sm\r\n                ", children: "Posici\u00F3n" }), _jsx("span", { className: "\r\n                  text-lg\r\n                  font-bold\r\n                  text-white\r\n                ", children: deposit.position
                                                                    ?? 'Sin datos' })] })] })] }), _jsxs("div", { className: "\r\n              bg-gradient-to-br\r\n              from-slate-800\r\n              to-slate-900\r\n\r\n              border\r\n              border-blue-900/30\r\n\r\n              rounded-3xl\r\n\r\n              p-6\r\n            ", children: [_jsxs("div", { className: "\r\n                flex\r\n                items-center\r\n                gap-3\r\n\r\n                mb-4\r\n              ", children: [_jsx(Waves, { size: 22, className: "\r\n                    text-cyan-400\r\n                  " }), _jsx("h3", { className: "\r\n                  text-lg\r\n                  font-bold\r\n                ", children: "Nivel agua" })] }), _jsxs("div", { className: "\r\n                text-4xl\r\n                font-black\r\n              ", children: [deposit.waterLevelCm
                                                        .toFixed(1), " cm"] })] }), _jsxs("div", { className: "\r\n              bg-gradient-to-br\r\n              from-slate-800\r\n              to-slate-900\r\n\r\n              border\r\n              border-blue-900/30\r\n\r\n              rounded-3xl\r\n\r\n              p-6\r\n            ", children: [_jsxs("div", { className: "\r\n                flex\r\n                items-center\r\n                gap-3\r\n\r\n                mb-4\r\n              ", children: [_jsx(Activity, { size: 22, className: "\r\n                    text-blue-400\r\n                  " }), _jsx("h3", { className: "\r\n                  text-lg\r\n                  font-bold\r\n                ", children: "Litros" })] }), _jsxs("div", { className: "\r\n                text-4xl\r\n                font-black\r\n              ", children: [(deposit.liters ?? 0)
                                                        .toLocaleString(), " L"] })] }), _jsxs("div", { className: "\r\n              bg-gradient-to-br\r\n              from-slate-800\r\n              to-slate-900\r\n\r\n              border\r\n              border-blue-900/30\r\n\r\n              rounded-3xl\r\n\r\n              p-6\r\n            ", children: [_jsxs("div", { className: "\r\n                flex\r\n                items-center\r\n                gap-3\r\n\r\n                mb-4\r\n              ", children: [_jsx(Battery, { size: 22, className: "\r\n                    text-green-400\r\n                  " }), _jsx("h3", { className: "\r\n                  text-lg\r\n                  font-bold\r\n                ", children: "Bater\u00EDa" })] }), _jsxs("div", { className: "\r\n                text-4xl\r\n                font-black\r\n              ", children: [deposit.battery, "%"] })] })] }), _jsx("div", { children: historyLoading ? (_jsx("div", { className: "\r\n                text-white\r\n              ", children: "Cargando hist\u00F3rico..." })) : (_jsx(WaterLevelChart, { title: "Hist\u00F3rico de nivel", data: history })) })] })] })] }));
};
export default DepositDetailPage;
